favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.749104
  brandStrength: 0.5071685
  lightness: 0.5017921
  brandColors:
    - '#265161'
    - '#10232A'
    - '#FFFFFF'
    - '#B0BEBF'
    - '#687B81'
  rhythmicContrast: 0.890681
typography_spectrum: 0.5089605
layout_spectrum: 0.234767
cta:
  bucket: null
  version: null
  domain: null
name: Versaille
